version: 1
formatters:
    simple:
      format: '[%(asctime)s - %(name)s -  %(levelname)s] %(message)s'
handlers:
  file_handler:
    class: logging.FileHandler
    filename: 'info.log'
    formatter: simple
    encoding: 'utf-8'

loggers:
  BasePage:
    level: INFO
    handlers: [file_handler]
  HomePage:
    level: INFO
    handlers: [file_handler]
  SearchResultPage:
    level: INFO
    handlers: [file_handler]
  ItemDetailPage:
    level: INFO
    handlers: [file_handler]
  BaskerPage:
    level: INFO
    handlers: [file_handler]